In [2]:
# feat. yj.Han

In [1]:
'''
문제 설명
격자선을 따라 움직이는 기계가 있습니다. 격자는 1 x 1 크기인 칸들로 이루어져 있습니다. 기계는 처음에 격자선의 교차점 위에 놓여있으며 상, 하, 좌, 우로 거리 1 만큼씩 움직일 수 있습니다.
이때, 기계가 움직인 기록이 주어지면 기계가 전부 움직인 후 기계의 동선에서 1x1 크기 정사각형이 몇 개가 보이는지 알아보려 합니다.
예를 들어 [상, 우, 하, 좌]로 기계를 움직였다면 기계의 동선은 아래 그림과 같으며, 기계의 동선에서 1x1 크기 정사각형 1개가 보입니다.

기계가 움직인 기록을 담은 배열 moves가 주어질때, 기계가 전부 움직인 후 기계의 동선에서 보이는 1x1 크기 정사각형 개수를 return 하도록 solution 함수를 완성해주세요.
제한사항
•	moves의 길이는 1 이상 500 이하입니다.
•	moves의 원소는 상, 하, 좌, 우를 나타내는 길이가 1인 문자열입니다.
•	상, 하, 좌, 우는 각각 “U”, “D”, “L”, “R”로 나타냅니다.
•	격자 평면은 무한히 크다고 가정합니다.
입출력 예
moves
return
[“U”, “R”, “D”, “L”, “U”, “R”, “D”, “L”]
1
[“U”, “U”, “R”, “D”, “L”, “L”, “L”, “U”, “R”, “D”, “D”, “D”, “L”, “U”, “R”, “R”, “R”, “D”, “L”, “U”]
5
[“U”, “L”, “D”, “R”, “R”, “D”, “D”, “L”, “U”, “U”]
1
입출력 예 설명
입출력 예 #1
문제의 그림과 같은 동선이 생기며, 1x1 크기 정사각형 1개가 보입니다.
입출력 예 #2
기계의 동선을 그려보면 아래 그림과 같습니다.

1x1 크기 정사각형이 5개 있습니다.
입출력 예 #3
기계의 동선을 그려보면 아래 그림과 같습니다.

1x1 크기 정사각형이 1개 있습니다.
문제 설명
격자선을 따라 움직이는 기계가 있습니다. 격자는 1 x 1 크기인 칸들로 이루어져 있습니다. 기계는 처음에 격자선의 교차점 위에 놓여있으며 상, 하, 좌, 우로 거리 1 만큼씩 움직일 수 있습니다.
이때, 기계가 움직인 기록이 주어지면 기계가 전부 움직인 후 기계의 동선에서 1x1 크기 정사각형이 몇 개가 보이는지 알아보려 합니다.
예를 들어 [상, 우, 하, 좌]로 기계를 움직였다면 기계의 동선은 아래 그림과 같으며, 기계의 동선에서 1x1 크기 정사각형 1개가 보입니다.

기계가 움직인 기록을 담은 배열 moves가 주어질때, 기계가 전부 움직인 후 기계의 동선에서 보이는 1x1 크기 정사각형 개수를 return 하도록 solution 함수를 완성해주세요.
제한사항
•	moves의 길이는 1 이상 500 이하입니다.
•	moves의 원소는 상, 하, 좌, 우를 나타내는 길이가 1인 문자열입니다.
•	상, 하, 좌, 우는 각각 “U”, “D”, “L”, “R”로 나타냅니다.
•	격자 평면은 무한히 크다고 가정합니다.
입출력 예
moves
return
[“U”, “R”, “D”, “L”, “U”, “R”, “D”, “L”]
1
[“U”, “U”, “R”, “D”, “L”, “L”, “L”, “U”, “R”, “D”, “D”, “D”, “L”, “U”, “R”, “R”, “R”, “D”, “L”, “U”]
5
[“U”, “L”, “D”, “R”, “R”, “D”, “D”, “L”, “U”, “U”]
1
입출력 예 설명
입출력 예 #1
문제의 그림과 같은 동선이 생기며, 1x1 크기 정사각형 1개가 보입니다.
입출력 예 #2
기계의 동선을 그려보면 아래 그림과 같습니다.

1x1 크기 정사각형이 5개 있습니다.
입출력 예 #3
기계의 동선을 그려보면 아래 그림과 같습니다.

1x1 크기 정사각형이 1개 있습니다.
'''

'\n문제 설명\n격자선을 따라 움직이는 기계가 있습니다. 격자는 1 x 1 크기인 칸들로 이루어져 있습니다. 기계는 처음에 격자선의 교차점 위에 놓여있으며 상, 하, 좌, 우로 거리 1 만큼씩 움직일 수 있습니다.\n이때, 기계가 움직인 기록이 주어지면 기계가 전부 움직인 후 기계의 동선에서 1x1 크기 정사각형이 몇 개가 보이는지 알아보려 합니다.\n예를 들어 [상, 우, 하, 좌]로 기계를 움직였다면 기계의 동선은 아래 그림과 같으며, 기계의 동선에서 1x1 크기 정사각형 1개가 보입니다.\n\n기계가 움직인 기록을 담은 배열 moves가 주어질때, 기계가 전부 움직인 후 기계의 동선에서 보이는 1x1 크기 정사각형 개수를 return 하도록 solution 함수를 완성해주세요.\n제한사항\n•\tmoves의 길이는 1 이상 500 이하입니다.\n•\tmoves의 원소는 상, 하, 좌, 우를 나타내는 길이가 1인 문자열입니다.\n•\t상, 하, 좌, 우는 각각 “U”, “D”, “L”, “R”로 나타냅니다.\n•\t격자 평면은 무한히 크다고 가정합니다.\n입출력 예\nmoves\nreturn\n[“U”, “R”, “D”, “L”, “U”, “R”, “D”, “L”]\n1\n[“U”, “U”, “R”, “D”, “L”, “L”, “L”, “U”, “R”, “D”, “D”, “D”, “L”, “U”, “R”, “R”, “R”, “D”, “L”, “U”]\n5\n[“U”, “L”, “D”, “R”, “R”, “D”, “D”, “L”, “U”, “U”]\n1\n입출력 예 설명\n입출력 예 #1\n문제의 그림과 같은 동선이 생기며, 1x1 크기 정사각형 1개가 보입니다.\n입출력 예 #2\n기계의 동선을 그려보면 아래 그림과 같습니다.\n\n1x1 크기 정사각형이 5개 있습니다.\n입출력 예 #3\n기계의 동선을 그려보면 아래 그림과 같습니다.\n\n1x1 크기 정사각형이 1개 있습니다.\n문제 설명\n격자선을 따라 움직이는 기계가 있습니다. 격자는 1 x 1 크

In [3]:
inputs_list = [['U', 'R', 'D', 'L', 'U', 'R', 'D', 'L'], 
               ['U', 'U', 'R', 'D', 'L', 'L', 'L', 'U', 'R', 'D', 'D', 'D', 'L', 'U', 'R', 'R', 'R', 'D', 'L', 'U'],
               ['U', 'L', 'D', 'R', 'R', 'D', 'D', 'L', 'U', 'U']]
answer_list = [1, 5, 1]

In [4]:
goal = 2

In [5]:
inputs = inputs_list[goal]
answer = answer_list[goal]

In [6]:
start_point = [[0,0]]

In [7]:
for i in inputs:
    if i == 'U':
        tmp_point = [start_point[-1][0]+1, start_point[-1][1]]
    elif i == 'D':
        tmp_point = [start_point[-1][0]-1, start_point[-1][1]]
    elif i == 'L':
        tmp_point = [start_point[-1][0], start_point[-1][1]-1]
    elif i == 'R':
        tmp_point = [start_point[-1][0], start_point[-1][1]+1]
    start_point.append(tmp_point)
    print(tmp_point)

[1, 0]
[1, -1]
[0, -1]
[0, 0]
[0, 1]
[-1, 1]
[-2, 1]
[-2, 0]
[-1, 0]
[0, 0]


In [8]:
print(start_point)

[[0, 0], [1, 0], [1, -1], [0, -1], [0, 0], [0, 1], [-1, 1], [-2, 1], [-2, 0], [-1, 0], [0, 0]]


In [9]:
len_list = len(start_point)
print(len_list)

11


In [10]:
x_list = []
y_list = []

In [11]:
for i in range(len_list):
    x_list.append(start_point[i][1])
    y_list.append(start_point[i][0])

In [12]:
print(x_list)
print(y_list)

[0, 0, -1, -1, 0, 1, 1, 1, 0, 0, 0]
[0, 1, 1, 0, 0, 0, -1, -2, -2, -1, 0]


In [13]:
x_min = min(x_list)
x_max = max(x_list)
y_min = min(y_list)
y_max = max(y_list)

In [14]:
print(x_min, x_max, y_min, y_max)

-1 1 -2 1


In [15]:
x_length = x_max - x_min
y_length = y_max - y_min

In [16]:
print(x_length, y_length)

2 3


In [17]:
import numpy as np

In [18]:
ud_list = np.zeros((y_length, x_length+1))
lr_list = np.zeros((y_length+1, x_length))

In [19]:
print(ud_list)
print(lr_list)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [20]:
x_list = np.array(x_list)
y_list = np.array(y_list)

In [21]:
x_list = x_list - x_min
y_list = y_list - y_min

In [22]:
print(x_list)
print(y_list)

[1 1 0 0 1 2 2 2 1 1 1]
[2 3 3 2 2 2 1 0 0 1 2]


In [23]:
for i in range(len_list - 1):
    x = x_list[i+1] - x_list[i]
    y = y_list[i+1] - y_list[i]
    if x < 0:
        lr_list[y_list[i], x_list[i]-1] = 1
    elif x > 0:
        lr_list[y_list[i], x_list[i]] = 1
    elif y < 0:
        ud_list[y_list[i]-1, x_list[i]] = 1
    elif y > 0:
        ud_list[y_list[i], x_list[i]] = 1

In [24]:
print(ud_list)
print(lr_list)

[[0. 1. 1.]
 [0. 1. 1.]
 [1. 1. 0.]]
[[0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 0.]]


In [25]:
type(ud_list)

numpy.ndarray

In [26]:
row, col = lr_list.shape

In [27]:
print(row, col)

4 2


In [28]:
cnt = 0

In [29]:
for i in range(row-1):
    for j in range(col):
        if (lr_list[i,j]==1) & (lr_list[i+1,j]==1) & (ud_list[i,j]==1) & (ud_list[i,j+1]==1):
            cnt += 1

In [30]:
if cnt == answer:
    print('정답입니다.')
else:
    print('오답입니다.')

정답입니다.
